### ISSUE TITLE
How to get the aws_ec2_transit_gateway, aws_ec2_transit_gateway_route_table and aws_ec2_transit_gateway_vpc_attachment objects

### ISSUE THREAD

**Issue by x280852** [awsandy/aws2tf#1]
Hi Andy,
First of all, great job!

One question, How can I get all the tgw resources (aws_ec2_transit_gateway, aws_ec2_transit_gateway_route_table and aws_ec2_transit_gateway_vpc_attachment)?

If I execute without specifying resources, I dont get any resource:

_t=no
loop through providers
/home/azureuser/aws2tf/generated/tf.576466822994
ls: cannot access '../../scripts/*-get-*no*.sh': No such file or directory_

if I execute specifying vpc, I just get the tgw attached to that vpc

if I execute -t transit-gateway, I receive an error

_t=transit
loop through providers
/home/azureuser/aws2tf/generated/tf.576466822994
135-get-transit-gateway-vpc-attachments.sh
aws.tf
Success! The configuration is valid.

201-get-transit-gateway.sh
could not find aws_ec2_transit_gateway__no.tf continuing ...

An error occurred (InvalidTransitGatewayID.Malformed) when calling the DescribeTransitGateways operation: Invalid Transit Gateway id no.
../../scripts/201-get-transit-gateway.sh: line 27: [: : integer expression expected_

Could you help me please? It is pretty interesting to get a tgw and all the objects related

Thank you very much!

**Comment by awsandy** [comment]
Hi,

Interestingly I've been working on that recently.

For now you'll have to pull every VPC that's connected to the Transit Gateway(s) like this:

./aws2tf.sh -t vpc -i vpc-aaaaaaa
./aws2tf.sh -t vpc -i vpc-bbbbbbb -c yes
./aws2tf.sh -t vpc -i vpc-ccccccc -c yes

the "-c yes" is new and allows you to pull stuff in a "cumulative" fashion. So you do the first run for the first vpc , the subsequent runs in a "cumulative mode"

As you go along you'll see errors in the output about undefined resources until you pull in the last VPC when it all should resolve.

I'm thinking about ways of adding a "-t tgw" that would automate the above for you and pull the resources in a different order so you don't see any errors.

One residual problem is I'm not seeing a way to handle VPN connections to transit gateways in Terraform, unless I've missed it in the docs.

The -t option should never be set to "no" by the way - it's intent is to pick out specific resources or groups of resources like eks or vpc. It can be omitted if needed.

I need to brush up the docs !

**Comment by awsandy** [comment]
The -t tgw -i tgw-xxxxxxxx.  option should be in better shape now
